development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: wakwak_works_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: wakwak_works_production
  ssl_params:
    verify_mode: OpenSSL::SSL::VERIFY_NONE
